#ifndef IDS_H
#define IDS_H

enum {
    ID_START = wxID_HIGHEST,
    ID_VIEW_EXP,
    ID_VIEW_CAT,
    ID_VIEW_YTD,
    ID_EXPENSE_NEW,
    ID_EXPENSE_EDIT,
    ID_EXPENSE_DEL,
    ID_EXPENSE_CATEGORIES,
    ID_EXPENSES_PANEL,
    ID_EXPENSES_MONTH,
    ID_EXPENSES_YEAR,
    ID_EXPENSES_PREVMONTH,
    ID_EXPENSES_NEXTMONTH,
    ID_EXPENSES_PREVYEAR,
    ID_EXPENSES_NEXTYEAR,
    ID_EXPENSES_LISTVIEW,
    ID_SETUPCATEGORIES_LB,
    ID_COUNT
};

#endif
